# Generated by Django 4.2.5 on 2023-10-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match_stats',
            name='points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
