# Generated by Django 4.2.5 on 2023-10-06 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_match_stats_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='email',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
