# Generated by Django 4.2.5 on 2023-10-06 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_coach_player_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='coachName',
        ),
        migrations.AddField(
            model_name='team',
            name='coachId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='player.coach'),
            preserve_default=False,
        ),
    ]
